DebianTest:
  image: "debian:9"
  before_script:
    - echo 'deb http://ftp.debian.org/debian stretch-backports main contrib non-free' >> /etc/apt/sources.list
    - apt -y update
    - apt-get -y -t stretch-backports install ansible
    - apt -y install git
    - echo 'localhost ansible_connection=local ansible_user=root' > inventory
  script:
    - ansible-playbook --syntax-check -i inventory test.yml
    - ansible-playbook -i inventory test.yml
