---
- name: Check if go is installed
  shell: which go
  failed_when: false
  changed_when: false
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ go_target_dir }}/go/bin"
  register: go_local_binary

- name: Query the local go version
  shell: "{{ go_target_dir }}/go/bin/go version |cut -d' ' -f3"
  failed_when: false
  changed_when: false
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ go_target_dir }}/go/bin"
  register: go_local_version

- name: Remove the old go package
  file:
    name: "{{ go_target_dir }}/go"
    state: absent
  when: (go_local_binary.stdout != "") and
        (go_local_version.stdout != go_target_version)

- name: Download the go package
  get_url:
    url: "https://storage.googleapis.com/golang/{{ go_target_version }}.linux-amd64.tar.gz"
    dest: "/tmp/{{ go_target_version }}.linux-amd64.tar.gz"
  when: (go_local_binary.stdout == "") or
        (go_local_version.stdout != go_target_version)

- name: Extract the go archive
  unarchive:
    src: "/tmp/{{ go_target_version }}.linux-amd64.tar.gz"
    dest: "{{ go_target_dir }}"
  when: (go_local_binary.stdout == "") or
        (go_local_version.stdout != go_target_version)

